meta_product_name: "Dog Runners"
meta_title: "Dog Runners - On-Demand Dog Running Service - Fit Dogs are Happy Dogs."
meta_description: "Dog Runners goal is to keep your dog fit and healthy when you do not have the time."
meta_image: "meta-data-img.png"                       # should exist in `app/assets/images/`

