# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed81187600a6856d84a722c0755d911a87cd0e82aa36607729b90a4c332c429c2505268897e71490befced10831a9e575e1c658511a88b5e09ea18b75df10ee4

test:
  secret_key_base: 25889dea1cd57482c20e8e463a0a3d79e9ca58f8d43787e9a1fe9f06f2734811d6fe73dc145ebf5123da12f8e692f2e6b5f26decdc5f8fe6adda398b80163f0c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
